# .github/workflows/test.yaml
on: [push, pull_request]
name: test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: make test-cover
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
